run_id: null

train: true
eval: True
quality_key: pp_diff

# general
model_id: deepseek-ai/deepseek-coder-1.3b-instruct
seed: 42
sol: true

# training
train_path: data/high_quality_dataset_quality_puzzles_train_1_pp_diff.json
# train_path: data/puzzles_high_fitness_archivetrain.json
batch_size: 8
accum_step: 1
num_epochs: 2

# testing
test_path: data/P3_test_emb_wizard3B.json
compile: false
k: 5
eval_batch_size: 16

slurm:
  cluster: jz
  gpu: a100